### ISSUE TITLE
Missing detail getter function for CustomEvent

### ISSUE THREAD

**Issue by the-dr-lazy** [purescript-web/purescript-web-events#14]
There is no getter function for `detail` property of `CustomEvent` type. Related to #13.

**Comment by bagrounds** [comment]
+1

I'm currently using this tiny FFI helper as a workaround.
```purs
-- FFI.purs
foreign import detail :: Event -> String -- <- I think this should probably return a Maybe String
```
```js
// FFI.js
exports.detail = customEvent => customEvent.detail
```

That said, I happen to stuff a string into the detail field, but the spec says it could be any type:

> "detail", optional and defaulting to null, of type any, that is an event-dependent value associated with the event.

https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

Not sure if it would make sense to have a polymorphic `CustomEvent a` type for this.

Note: I'm using this `CustomEvent` in order to send events from javascript into purescript.
In JS, I dispatch an event to an application specific dom element, and in my halogen app I register an event listener on that same dom element. The events are generated by a third party library, for which there is no purescript port or wrapper. This seems fairly hacky to me, so if there's a more purescripty way to do this, I'd appreciate any tips :).
