### ISSUE TITLE
Extract value from a web component input

### ISSUE THREAD

**Issue by nishirken** [purescript-web/purescript-web-events#28]
Hello, I have a web component input.
![Screenshot from 2022-10-27 23-54-29](https://user-images.githubusercontent.com/17808169/198386358-231045f1-2dc2-4291-a64e-b71798055349.png)

It fires an input event with the target/currentTarget of the web component itself, not HTMLInputElement.
![Screenshot from 2022-10-27 23-55-18](https://user-images.githubusercontent.com/17808169/198386375-a7bff051-501d-43ee-acf7-b4ceb6274628.png)
As a result fromEventTarget returns Nothing.
Latest versions of purescript-web-events and purescript-web-html are installed.
How to get around it?

**Comment by garyb** [comment]
Just to check I understand correctly - the problem here is when trying to use `HTMLInputElement.fromEventTarget`?

If the custom element doesn't extend `HTMLInputElement` then that would be the expected behaviour. You should be able to use `HTMLElement.fromEventTarget` at least, but if you want to access properties/call methods on the custom element that are outside of the prototype it's extending you'll have to write your own FFI to deal with that I'm afraid.

**Comment by nishirken** [comment]
Yes, I used `HTMLInputElement.fromEventTarget` because there is a limited set of elements with the value property.
I've already solved the problem with FFI.
Thanks for the response. The issue can be closed.
